import { CRMBookingProduct } from '../../src/interfaces/crm';

export const mockCRMBookingProducts: CRMBookingProduct[] = [
  {
    ftts_bookingproductid: '001',
    ftts_entitlementconfirmation: 'entconfirm353525',
    ftts_personalreferencenumber: 'ABC123',
    ftts_reference: 'REF001',
    ftts_testaccommodation: '1,2,3',
    ftts_testdate: '2020-06-23T07:00:00Z',
    ftts_testenginebookingupdated: '2020-06-21T07:00:00Z',
    ftts_testlanguage: 2,
    ftts_voiceoverlanguage: 675030005,
    _ftts_candidateid_value: 'candidate1',
    ftts_CandidateId: {
      contactid: 'C001',
      ftts_firstandmiddlenames: 'Carl',
      lastname: 'Teslington',
      birthdate: '1980-12-03',
      gendercode: 1,
      address1_line1: 'Floor 15',
      address1_line2: 'ECJU',
      address1_line3: '50 Victoria Street',
      address1_city: 'London',
      address1_county: null,
      address1_postalcode: 'SW1H 0TL',
    },
    ftts_productid: {
      ftts_testenginetesttype: 4,
    },
    ftts_bookingid: {
      ftts_testcentre: {
        ftts_remit: 675030000,
        ftts_testenginedeliverymodel: 1,
        ftts_testenginetestcentrecode: 'TESTCENTRE-1',
        ftts_regiona: false,
        ftts_regionb: true,
        ftts_regionc: false,
      },
      ftts_LicenceId: { ftts_licence: 'WENDY68245925' },
    },
  },
  {
    ftts_bookingproductid: '002',
    ftts_entitlementconfirmation: 'entbonfirm353525',
    ftts_personalreferencenumber: 'BCD8742',
    ftts_reference: 'REF002',
    ftts_testaccommodation: '1',
    ftts_testdate: '2020-05-12T11:00:00Z',
    ftts_testenginebookingupdated: '2020-05-11T12:00:00Z',
    ftts_testlanguage: 2,
    ftts_voiceoverlanguage: 675030006,
    _ftts_candidateid_value: 'candidate2',
    ftts_CandidateId: {
      contactid: 'C002',
      ftts_firstandmiddlenames: 'Marl',
      lastname: 'Meslington',
      birthdate: '1981-04-13',
      gendercode: 2,
      address1_line1: 'gwgewg',
      address1_line2: null,
      address1_line3: 'fasf',
      address1_city: 'Manchester',
      address1_county: null,
      address1_postalcode: 'M1 7ER',
    },
    ftts_productid: {
      ftts_testenginetesttype: 2,
    },
    ftts_bookingid: {
      ftts_testcentre: {
        ftts_remit: 675030001,
        ftts_testenginedeliverymodel: 1,
        ftts_testenginetestcentrecode: 'IHTTC-TESTCENTRE-2',
        ftts_regiona: true,
        ftts_regionb: false,
        ftts_regionc: true,
      },
      ftts_LicenceId: { ftts_licence: 'CARLY26245910' },
    },
  },
];
